server:
  port: 3333

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api/doc
